{% set version = "2.1.10" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rmixmod
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Rmixmod_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rmixmod/Rmixmod_{{ version }}.tar.gz
  sha256: 96d592c36a456ab744b5e885dbbc929e4d1d2a5f4d8489c9c224fe353f0af189
  patches:
    - patches/0001-add-pthread.patch

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-rcppeigen                  # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.11.0
    - r-rcppeigen
  run:
    - r-base
    - r-rcpp >=0.11.0
    - r-rcppeigen

test:
  commands:
    - $R -e "library('Rmixmod')"           # [not win]
    - "\"%R%\" -e \"library('Rmixmod')\""  # [win]

about:
  home: http://www.mixmod.org
  license: GPL-3.0-only
  summary: Interface of 'MIXMOD' software for supervised, unsupervised and semi-supervised classification with mixture modelling.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
