appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: m1mnzKwZwLgWrA0Az4Hl0CiGCSxtQThX9O0WcPx2Apwwm231t1d0KUN6EBnMBFzhE6rIN0EENewW2u3zIJ3vdLGJPCJqbh1QNuv4h7XHJlJcWgBL11Bf31//w0MHI1ZVysKtmq6JF9VDrptF9JFgr4zuEPXDouwqkzirGPUy34n8HeTkTe8/6QnR/4cEZobLuiAB06cfMoNL3Omd03dsloE8ct8yjTqNby70jDzEIzn7gEgDTlpMfBSfOoO1YDrJz2Kbq7cIVMv7YLw75JSU+5xYTLCjCoO1wGBfXEGTbSG8s/EdJMrZeeF3QEYbYB4y2y5hhKzr3kqbf8o+SM9Kxzv7g3t2BCnBdrCFxSlnskprgepybEy9Gx4UbyGAT7k8A+BmLJL0tSmk5s0CRykVNL975Fe/XFgtaMJikGd7/2NIlzwekOl2zBcG9SBiS0jvTddk5EmlDJN8ll/ylAUFsy6tzrkT30hWlbk7wFKOmgTPv2NtCXpYdrqDPIG26ebUMoYWBWFv/oRps/LTiRaWX2dA4Cq+swBSMM2NxnmIpRmCyD2ddZjhyafOcuCMEKC5wpo7h9l/VbBRG0BDkihm3ytOH1T/WBTOReVBB27L8ebR0xZj67Sv8SoeGiT/E3hJWXV8sw05mTm3BVlCPJDVENiYSuOXe+yGnW9gVNjHpLw=}
